version: '3.8'
services:
  web:
    container_name: backend
    build: .
    command: /app/src/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./src/.env
    depends_on:
      - db
  
  db:
    container_name: postgres_db
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_db
volumes:
  postgres_data: